services:
  elasticsearch:
    build: .
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ./ops/dic:/usr/share/elasticsearch/config/dic

  # kibana:
  #   container_name: kibana
  #   image: kibana:8.15.1
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   ports:
  #     - "5601:5601"
